name: Security with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
     branches: 
        [main]
  schedule:
          - cron: '15 5 * * 3'
            


jobs:
 
 test:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [java]
        build-mode: [autobuild]
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      # Initializes CodeQL tools and creates a codebase for analysis.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      