name: Security with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
     branches: 
        [main]
  schedule:
          - cron: '15 5 * * 3'
            


jobs:
 
 test:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [java]
        build-mode: [autobuild]
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      # Initializes CodeQL tools and creates a codebase for analysis.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}



      - name: Analyze with CodeQL
        run: |
           codeql database analyze ${{github.workspace}} --format=sarif-latest --output=codeql-results.sarif
    
   
      - name: Upload CodeQL results
        uses: actions/upload-artifact@v2
        with:
            name: codeql-results
            path: codeql-results.sarif