name: Java Junit and Selenium

on:
  push:
    branches:
      - main


jobs:

   test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '11'
    

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Run Junit tests
      run: mvn test 

   selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'oracle' 
            java-version: '11'
      - name: Run Junit tests
        run: mvn test  -Dtest=TestSelenium
     
      


   send_email_notification:
        name: Send Email Notification
        runs-on: ubuntu-latest
        needs: test
        if: ${{ needs.test.result == 'success' }}
        steps:
          - name: Send Email
            if: always()
            uses: hilarion5/send-mail@v1
            with:
                smtp-server: ${{ secrets.SMTP_NAME }}
                smtp-port: 2525
                smtp-secure: false
                from-email: ${{ secrets.FROM_EMAIL }}
                to-email: ${{ secrets.SMTP_TO_EMAIL }}
                username: ${{ secrets.SMTP_USERNAME }}
                password: ${{ secrets.SMTP_PASSWORD }}
                subject: Workflows Status Notifications
                body: |
                
                    The build was ${{ needs.test.result }}.
                    ----------------------------------------------
                    Une nouvelle version de notre projet est disponible. Vous pouvez consulter la source du projet ici : https://github.com/${{ github.repository }}

                    ---------------------------------------------  

   codacy-analysis-cli:
        name: Codacy Analysis CLI
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@main

          - name: Run Codacy Analysis CLI
            uses: codacy/codacy-analysis-cli-action@master